### ISSUE TITLE
Also provide the Radare2 cheatsheet into a PDF file

### ISSUE THREAD

**Issue by E3V3A** [pwntester/cheatsheets#3]
Would be great if you could also provide the Radre2 cheatsheet as a printable PDF file. 
https://github.com/pwntester/cheatsheets/blob/master/radare2.md

**Comment by pwntester** [comment]
Hi, I will see If I can get it easily formated and printed to a PDF. BTW, the cheatsheet has been migrated to the radare2 repo. Its now in /docs/intro.md and will be updated by more people there, so please use that version

**Comment by ahhh** [comment]
Hey @pwntester I couldn't locate the cheatsheet in the official radare2 repo, under /docs/intro.md or /doc/intro.md. Therefore I've updated this branch with my changes, however I'de be pleased to be pointed to the official location of the cheat sheet!

**Comment by pwntester** [comment]
Ok, closing then since r2 should be the official repo
